2525nicole/memo-recall

- .github/workflows/lint.yml
- #5 
- mainブランチへのPushまたはPR作成時に自動でLinterとFormatterが実行される環境を構築した
> CIの環境構築（Linter/Formatter）

- .github/workflows/test.yml
- #5 
- test.ymlのnameを`Test`に修正した
> test.ymlのnameを修正

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.slim
- config/application.rb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20240602130427_devise_create_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- #86 
以下を導入した
- devise gem
- devise-i18n
> devise gemの導入

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/routes.rb
- #95 
letter_opener_web gemを導入した
> letter_opener_web gemの導入

- app/models/category.rb
- app/models/memory.rb
- app/models/user.rb
- db/migrate/20240605121710_create_memories.rb
- db/migrate/20240605123536_create_categories.rb
- db/migrate/20240605124545_add_category_id_to_memories.rb
- db/migrate/20240606041709_add_unique_index_to_categories_name_and_user_id.rb
- db/schema.rb
- spec/factories/categories.rb
- spec/factories/memories.rb
- spec/models/category_spec.rb
- spec/models/memory_spec.rb
- #97 
- #98 
以下を行った
- モデルを作成
- Memory
- Category
- アソシエーションの設定
- バリデーションの追加
> MemoryモデルとCategoryモデルの作成

- .github/workflows/lint.yml
なし
- GitHub Actions実行時にslim_lint.ymlの設定を使用するように修正した
> GitHub Actions実行時にslim_lint.ymlの設定を使用するように修正

- .github/workflows/lint.yml
- app/controllers/categories_controller.rb
- app/models/category.rb
- app/views/categories/edit.html.slim
- app/views/categories/index.html.slim
- app/views/categories/new.html.slim
- app/views/layouts/application.html.slim
- config/locales/ja.yml
- config/locales/translation_ja.yml
- config/routes.rb
- db/migrate/20240608143309_add_not_null_constraints_to_categories_and_memories.rb
- db/migrate/20240612121649_add_length_constraint_to_name_in_categories.rb
- db/schema.rb
- package-lock.json
- package.json
- spec/requests/categories_spec.rb
- #43 
- #101 
- #102 
- viewに最低限のcssを当てて機能が確認できる状態にした
- 後にモーダル化する以下の機能も一旦ページとして作成した
- カテゴリーの登録
- カテゴリーの編集
> Categoryコントローラーとビューを作成した

- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/controllers/category_memories_controller.rb
- app/controllers/memories_controller.rb
- app/models/category.rb
- app/models/memory.rb
- app/views/categories/edit.html.slim
- app/views/categories/index.html.slim
- app/views/categories/new.html.slim
- app/views/category_memories/index.html.slim
- app/views/memories/edit.html.slim
- app/views/memories/index.html.slim
- app/views/memories/new.html.slim
- app/views/memories/random.html.slim
- config/locales/ja.yml
- config/locales/translation_ja.yml
- config/routes.rb
- spec/requests/memories_spec.rb
- #15 
- #26 
- #27 
- #28 
- #29 
- #31 
- #39 
- #60  
- #104 
- #105 
- #106  
- viewに最低限のcssを当てて機能が確認できる状態にした
- 後にモーダル化する以下の機能も一旦ページとして作成した
- 思い出の登録
- 思い出の編集
> Memory関連のコントローラー、ビュー、編集、削除、表示機能を作成

- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/controllers/category_memories_controller.rb
- app/controllers/memories_controller.rb
- app/models/category.rb
- app/models/memory.rb
- app/views/categories/index.html.slim
- app/views/category_memories/index.html.slim
- app/views/kaminari/_first_page.html.slim
- app/views/kaminari/_gap.html.slim
- app/views/kaminari/_last_page.html.slim
- app/views/kaminari/_next_page.html.slim
- app/views/kaminari/_page.html.slim
- app/views/kaminari/_paginator.html.slim
- app/views/kaminari/_prev_page.html.slim
- app/views/memories/index.html.slim
- config/initializers/kaminari_config.rb
- config/locales/ja.yml
- #85 
kaminari gemを使用し、ページネーションを追加した
> ページネーションを追加

- app/models/memory.rb
- app/views/memories/new.html.slim
- #111 
- 登録できる思い出の最大文字数を400文字に設定した
- 関連して、思い出登録ページのcssを調整した
> 思い出の最大文字数の設定

- app/views/memories/index.html.slim
- app/views/memories/random.html.slim
- #112 
- #115 
トップページと思い出の一覧表示ページで以下のとおり表示されるように設定を追加した
- 登録時に入力された改行が反映される
- 左揃えで表示される
> 思い出の表示設定を追加

- app/views/layouts/application.html.slim
- #128 
- PCで表示するbody要素の横幅を決め、body要素の外側のcolorを設定した
> PCで表示するbody要素の横幅を決定

- app/views/memories/_memory.html.slim
- app/views/memories/random.html.slim
- #132 
- トップページのレイアウトを調整
- 思い出表示をTurbo Frame化
> トップページのTurbo Frame化とレイアウト調整

- app/controllers/memories_controller.rb
- app/views/categories/_form.html.slim
- app/views/categories/edit.html.slim
- app/views/categories/index.html.slim
- app/views/categories/new.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/layouts/_flash.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/memories/_form.html.slim
- app/views/memories/_memory.html.slim
- app/views/memories/random.html.slim
- #22 
- ハンバーガーメニューの作成
- トップページのレイアウト調整
- ヘッダー、flashメッセージのレイアウト調整
> ハンバーガーメニューの作成

- app/views/categories/_form.html.slim
- app/views/categories/edit.html.slim
- app/views/categories/new.html.slim
- #138 
- カテゴリー登録/編集モーダルのレイアウトを調整
> カテゴリー登録/編集モーダルのレイアウトを調整

- app/helpers/application_helper.rb
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- #139 
- #140 
- #141 
以下の位置を修正し、application.html.slimのコードを整えた
- フローティングアクションボタン
- flashメッセージ
> フローティングアクションボタンとflashメッセージの位置を修正

- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
> max-w-screenの幅をsmに変更

- app/views/layouts/_flash.html.slim
> flashのスタイルを調整

- app/views/devise/passwords/edit.html.slim
- app/views/layouts/_flash.html.slim
- #54 
- 未ログイン時のパスワード再設定ページのレイアウトを調整
- #149 の対応漏れ
> パスワード再設定ページのレイアウトを調整

- app/views/categories/_category.html.slim
- app/views/categories/_form.html.slim
- app/views/categories/edit.html.slim
- app/views/categories/index.html.slim
- app/views/categories/new.html.slim
- app/views/category_memories/index.html.slim
- app/views/devise/confirmations/new.html.slim
- app/views/devise/passwords/edit.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/devise/shared/_error_messages.html.slim
- app/views/layouts/_category_description.html.slim
- app/views/layouts/_flash.html.slim
- app/views/layouts/_footer.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/memories/_form.html.slim
- app/views/memories/_memory.html.slim
- app/views/memories/_random_description.html.slim
- app/views/memories/edit.html.slim
- app/views/memories/index.html.slim
- app/views/memories/new.html.slim
- app/views/memories/random.html.slim
- app/views/welcome/index.html.slim
- #153 
CSSのブレークポイントを`md:`から`sm:`〜に変更
> CSSのブレークポイントを`md:`から`sm:`〜に変更

- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
- #160
- footerとフローティングアクションボタンの配置を修正
> footerとフローティングアクションボタンの配置を修正

- app/views/category_memories/index.html.slim
- app/views/memories/index.html.slim
- #164 
- カテゴリー別思い出一覧ページのレイアウトを調整 
- 思い出未登録時のメッセージの文言を修正
> カテゴリー別思い出一覧ページのレイアウトを調整

- app/views/layouts/_header.html.slim
- #168 
- 他ページのリンクと同様に、hover時に色が薄くなるように修正
> ハンバーガーメニューの文字色を修正

- app/assets/stylesheets/application.tailwind.css
- app/views/categories/_category.html.slim
- app/views/categories/_form.html.slim
- app/views/categories/index.html.slim
- app/views/category_memories/index.html.slim
- app/views/devise/confirmations/new.html.slim
- app/views/devise/passwords/edit.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/devise/shared/_links.html.slim
- app/views/layouts/_footer.html.slim
- app/views/layouts/_header.html.slim
- app/views/memories/_form.html.slim
- app/views/memories/_memory.html.slim
- app/views/memories/index.html.slim
- app/views/memories/random.html.slim
- app/views/welcome/index.html.slim
- #169 
- カスタムcssクラスを作成
- ボタン
- リンク
> カスタムクラスを作成

- public/404.html
> 404ページにサービスURLを追記

- app/javascript/controllers/character_counter_controller.js
- app/models/category.rb
- app/models/memory.rb
- app/views/categories/_form.html.slim
- app/views/categories/edit.html.slim
- app/views/categories/new.html.slim
- app/views/category_memories/index.html.slim
- app/views/memories/_form.html.slim
- app/views/memories/random.html.slim
- db/migrate/20240908122857_change_category_name_limit_to15.rb
- db/schema.rb
- #195 
- #196 
- 思い出とカテゴリーの登録可能な最大文字数を変更
- 思い出/カテゴリーフォームに文字数カウンターを追加
- カテゴリー名表示箇所の修正
> 思い出とカテゴリーの最大文字数を変更

- app/assets/stylesheets/application.tailwind.css
- app/views/memories/_form.html.slim
- #200 
- 思い出登録フォームのカテゴリーエリアのレイアウトを調整
- text_area, text_field, selectボックスのcssを変更
> 思い出登録フォームのレイアウトとcssを修正

- app/controllers/memories_controller.rb
- #194 
- 思い出の更新/更新時にトランザクションを追加
> 思い出の登録、更新処理にトランザクションを追加

- app/views/categories/_form.html.slim
> カテゴリーフォームの不要な記述を削除

- app/views/layouts/application.html.slim
- #211 
- #219 
FABの以下を修正
- 表示するページ（思い出関連のページのみ）
- アイコンと位置
> FABの表示ページとスタイルを修正

- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/memories/_memory.html.slim
- app/views/memories/random.html.slim
- なし
以下のz-indexを調整した
- 思い出のランダム表示ページ
- memoryパーシャル
> z-indexの調整

- app/views/memories/_memory_with_more_link.html.slim
- 軽微な修正のため、なし
- 思い出ランダム表示ページにおける初回思い出登録後のテンプレートを追加
> 思い出ランダム表示ページにおける初回思い出登録後のテンプレートを追加

- app/views/category_memories/index.html.slim
- app/views/memories/index.html.slim
- #225 
カテゴリー別思い出一覧ページのデザインを修正
> カテゴリー別思い出一覧ページのデザイン修正

- app/views/categories/index.html.slim
- app/views/category_memories/index.html.slim
- app/views/memories/index.html.slim
> ログイン後ページ全体のpx値を統一

- app/views/categories/_form.html.slim
- app/views/devise/registrations/edit.html.slim
- #214 
- アカウント設定画面のデザイン修正
- カテゴリーフォームの不要なコード削除
> アカウント設定画面のデザイン修正

- app/views/devise/shared/_error_messages.html.slim
- app/views/layouts/_flash.html.slim
> flashメッセージのデザインを修正

- app/helpers/memories_helper.rb
- app/views/layouts/_header.html.slim
- app/views/memories/_memory_with_more_link.html.slim
- app/views/memories/random.html.slim
- #242 
- ログイン後のトップページのパスをroot_pathからauthenticated_root_pathに修正
> ログイン後のトップページのパスをroot_pathからauthenticated_root_pathに修正

- config/environments/test.rb
- spec/factories/categories.rb
- spec/factories/memories.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
> Userモデルのテストを作成

- spec/models/memory_spec.rb
> Memoryモデルのテストを作成

- spec/models/category_spec.rb
> Categoryモデルのテストを作成

- app/controllers/memories_controller.rb
- app/helpers/memories_helper.rb
- app/views/memories/create.turbo_stream.slim
> 思い出登録時の処理を修正

- app/views/welcome/index.html.slim
- #253 
- welcomeページのサービス説明文を修正
- 思い出登録用のFABを一部ページから削除したため、実態に沿うよう文面を修正した
> welcomeページのサービス説明文を修正

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.tailwind.css
- config/environments/test.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/system/users_spec.rb
> Usersのシステムテストを作成

- spec/system/memories_spec.rb
> Memoriesのシステムテストを作成

- spec/system/categories_spec.rb
> Categoriesのシステムテストを作成

- spec/system/category_memories_spec.rb
- #261 
- CategoryMemoriesのシステムテストを作成
> CategoryMemoriesのシステムテストを作成

- app/controllers/categories_controller.rb
- app/controllers/memories_controller.rb
- app/helpers/memories_helper.rb
- app/views/categories/_no_categories_message.html.slim
- app/views/categories/destroy.turbo_stream.slim
- app/views/categories/index.html.slim
- app/views/category_memories/_no_category_memories_message.html.slim
- app/views/category_memories/index.html.slim
- app/views/memories/_no_memories_message.html.slim
- app/views/memories/destroy.turbo_stream.slim
- app/views/memories/index.html.slim
- app/views/memories/random.html.slim
- #266 
- 思い出、カテゴリー削除後登録が0件の際にメッセージを表示するように修正
> 思い出、カテゴリー削除後登録が0件の際にメッセージを表示するように修正

- app/views/memories/_form.html.slim
- #274 
- 思い出フォーム内カテゴリー説明モーダルの文字色を修正
> 思い出フォーム内カテゴリー説明モーダルの文字色を修正

- app/controllers/memories_controller.rb
- app/models/memory.rb
- app/views/memories/_form.html.slim
- spec/models/memory_spec.rb
- #277 
- MemoriesControllerで行っていた処理をモデルに移動
> MemoriesControllerで行っていた処理をモデルに移動

- README.md
- bin/setup
- #173 
- READMEにサービスの説明を追記
- bin/setupで開発環境のセットアップができるようにした
> READMEをアップデート

- app/controllers/categories_controller.rb
- app/controllers/category_memories_controller.rb
- app/controllers/memories_controller.rb
- app/views/categories/_category_description.html.slim
- app/views/categories/_form.html.slim
- app/views/categories/index.html.slim
- app/views/category_memories/index.html.slim
- app/views/memories/index.html.slim
> Category関連のリファクタリング（コードレビュー前）

- app/views/categories/_category.html.slim
- app/views/categories/_category_description.html.slim
- app/views/categories/index.html.slim
- app/views/category_memories/index.html.slim
- app/views/devise/passwords/edit.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/registrations/edit.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/memories/_memory.html.slim
- app/views/memories/index.html.slim
- app/views/memories/random/_memory_with_more_link.html.slim
- app/views/memories/random/_random_description.html.slim
- app/views/memories/random/show.html.slim
> コード内の空行を統一した

- app/views/devise/registrations/edit.html.slim
> 不要な「戻る」リンクを削除

- .rubocop.yml
- config/application.rb
> 不要なファイルと記述を削除

- config/initializers/devise.rb
- spec/factories/users.rb
- spec/system/users_spec.rb
> パスワードを8文字以上にする

- config/environments/production.rb
- config/initializers/devise.rb
- #299 
以下を修正した
- 送信元メールアドレス
- メールの差出人名
> 配信メールの情報を修正

- .rubocop.yml
- #317 
- .rubocop.ymlにTargetRubyVersionを設定
> TargetRubyVersionを追記

- app/controllers/memories_controller.rb
- app/models/memory.rb
- app/views/memories/_form.html.slim
- spec/models/memory_spec.rb
- #312 
- 思い出登録時のカテゴリー登録処理をモデルのコールバックを使用するように変更
> 思い出登録時のカテゴリー登録方法を変更

- README.md
> リリース前のREADMEアップデート

- app/views/memories/_memory.html.slim
- なし
- 思い出の表示にhメソッドを追加し、htmlタグにエスケープ処理を行うようにした
> 思い出の表示にhメソッドを追加
